branches:
  only:
  - master
  - develop
  - /^issue.*$/

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: linux
      dist: trusty
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.3
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      services: docker
      env: DOCKER_IMAGE=ubuntu:16.04
      sudo: required
    - os: linux
      dist: trusty
      services: docker
      env: DOCKER_IMAGE=ubuntu:18.04
      sudo: required
    - os: osx
      osx_image: xcode9.2
      sudo: required
      env: SWIFT_SNAPSHOT=4.0.3
    - os: osx
      osx_image: xcode9.4
      sudo: required
      env: SWIFT_SNAPSHOT=4.1.2
    - os: osx
      osx_image: xcode10
      sudo: required

before_install:
- chmod +x build.sh

script:
- ./build.sh
